/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/monsters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monsters, newest first */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of monsters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonsterPage"];
                    };
                };
                /** @description Invalid pagination */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create a monster */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMonsterRequest"];
                };
            };
            responses: {
                /** @description Monster created */
                201: {
                    headers: {
                        /** @description URL of the created resource */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Monster"];
                    };
                };
                /** @description Invalid body or malformed JSON */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Body larger than 10kb */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monsters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Monster id (UUID) */
                id: string;
            };
            cookie?: never;
        };
        /** Get a monster */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Monster id (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The monster */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Monster"];
                    };
                };
                /** @description Invalid id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Monster not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a monster (soft delete; its battles are kept) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Monster id (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monster deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Monster not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update some fields of a monster */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Monster id (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMonsterRequest"];
                };
            };
            responses: {
                /** @description The updated monster */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Monster"];
                    };
                };
                /** @description Invalid id or body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Monster not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Body larger than 10kb */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/battles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List past battles, newest first (without turns) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of battle summaries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BattleSummaryPage"];
                    };
                };
                /** @description Invalid pagination */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Simulate a battle between two monsters and store the result */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBattleRequest"];
                };
            };
            responses: {
                /** @description Battle simulated and stored, with every turn */
                201: {
                    headers: {
                        /** @description URL of the created resource */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Battle"];
                    };
                };
                /** @description Invalid body, or both ids are the same monster */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description One of the monsters does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Body larger than 10kb */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Battle id (UUID) */
                id: string;
            };
            cookie?: never;
        };
        /** Get a battle with every turn */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Battle id (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The battle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Battle"];
                    };
                };
                /** @description Invalid id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Battle not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a battle (its monsters are not affected) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Battle id (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Battle deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Battle not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded (see the RateLimit and Retry-After headers) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unexpected error; the cause is logged, never returned */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up (never checks the database) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthLive"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: the database answers (also served at /health) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthReady"];
                    };
                };
                /** @description Database is down */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthReady"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateMonsterRequest: {
            name: string;
            hp: number;
            attack: number;
            defense: number;
            speed: number;
            /** Format: uri */
            imageUrl: string;
        };
        UpdateMonsterRequest: {
            name?: string;
            hp?: number;
            attack?: number;
            defense?: number;
            speed?: number;
            /** Format: uri */
            imageUrl?: string;
        };
        /** @description monsterAId and monsterBId must be different. On a full tie, monster A attacks first. */
        CreateBattleRequest: {
            /** Format: uuid */
            monsterAId: string;
            /** Format: uuid */
            monsterBId: string;
        };
        Monster: {
            /** Format: uuid */
            id: string;
            name: string;
            hp: number;
            attack: number;
            defense: number;
            speed: number;
            /** Format: uri */
            imageUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MonsterPage: {
            items: {
                /** Format: uuid */
                id: string;
                name: string;
                hp: number;
                attack: number;
                defense: number;
                speed: number;
                /** Format: uri */
                imageUrl: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            total: number;
            page: number;
            pageSize: number;
        };
        BattleSummary: {
            /** Format: uuid */
            id: string;
            /** @description The monster exactly as it was when the battle happened */
            monsterA: {
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: uri */
                imageUrl: string;
                hp: number;
                attack: number;
                defense: number;
                speed: number;
            };
            /** @description The monster exactly as it was when the battle happened */
            monsterB: {
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: uri */
                imageUrl: string;
                hp: number;
                attack: number;
                defense: number;
                speed: number;
            };
            /** Format: uuid */
            winnerId: string;
            /** Format: uuid */
            loserId: string;
            totalTurns: number;
            /** Format: date-time */
            createdAt: string;
        };
        BattleSummaryPage: {
            items: {
                /** Format: uuid */
                id: string;
                /** @description The monster exactly as it was when the battle happened */
                monsterA: {
                    /** Format: uuid */
                    id: string;
                    name: string;
                    /** Format: uri */
                    imageUrl: string;
                    hp: number;
                    attack: number;
                    defense: number;
                    speed: number;
                };
                /** @description The monster exactly as it was when the battle happened */
                monsterB: {
                    /** Format: uuid */
                    id: string;
                    name: string;
                    /** Format: uri */
                    imageUrl: string;
                    hp: number;
                    attack: number;
                    defense: number;
                    speed: number;
                };
                /** Format: uuid */
                winnerId: string;
                /** Format: uuid */
                loserId: string;
                totalTurns: number;
                /** Format: date-time */
                createdAt: string;
            }[];
            total: number;
            page: number;
            pageSize: number;
        };
        Battle: {
            /** Format: uuid */
            id: string;
            /** @description The monster exactly as it was when the battle happened */
            monsterA: {
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: uri */
                imageUrl: string;
                hp: number;
                attack: number;
                defense: number;
                speed: number;
            };
            /** @description The monster exactly as it was when the battle happened */
            monsterB: {
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: uri */
                imageUrl: string;
                hp: number;
                attack: number;
                defense: number;
                speed: number;
            };
            /** Format: uuid */
            winnerId: string;
            /** Format: uuid */
            loserId: string;
            totalTurns: number;
            /** Format: date-time */
            createdAt: string;
            turns: {
                turn: number;
                attackerId: string;
                defenderId: string;
                damage: number;
                defenderHpAfter: number;
            }[];
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR" | "INVALID_JSON" | "NOT_FOUND" | "ROUTE_NOT_FOUND" | "PAYLOAD_TOO_LARGE" | "RATE_LIMITED" | "INTERNAL_ERROR";
                message: string;
                /** @description Only present on VALIDATION_ERROR */
                issues?: {
                    path: string;
                    message: string;
                }[];
            };
        };
        HealthLive: {
            /** @constant */
            status: "ok";
        };
        HealthReady: {
            /** @enum {string} */
            db: "up" | "down";
            /** @enum {string} */
            status: "ok" | "error";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
